name: Proposition de fonctionnalité (Feature/Pull Request)
description: Suggérer une idée pour ce projet
title: "Votre titre..."
labels: ["pull request", "Feature"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Laissez votre créativité prendre le dessus!
  - type: textarea
    id: feat
    attributes:
      label: Quelle est votre idée ?
      description: Que souhaitez vous accomplir ?
      placeholder: Racontez nous votre idée!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Aperçu de votre fonctionnalité
      description: Ajoutez des captures d'écran (si nécessaire).
  - type: checkboxes
    id: terms
    attributes:
      label: Template de contribution
      description: En soumettant cette issue, vous acceptez de suivre les règles du [Template de contribution](https://github.com/xunita/DLL_2023/blob/main/TEMPLATE-CONTRIBUTION.md)
      options:
        - label: J'accepte de suivre les règles du Template de contribution
          required: true
